#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# 51-postInstall-apt-install-ev3dev
#
# This is one of a series of scripts that live in /root/postInstall. They are
# placed there to avoid being read by casual users and are intended to be
# executed immediately after the VM is created to set up host specific 
# configuration.
#
# Install base apps for this machine
#
# Copyright (C) 2014-2015 Ralph Hempel <rhempel@hempeldesigngroup.com>
#
# See LICENSE for https://github.com/rhempel/pxeBoot
# -----------------------------------------------------------------------------

. /root/postInstall/postInstall-setupvars

# -----------------------------------------------------------------------------
# Install additional apps for this machine

# -----------------------------------------------------------------------------
# Install and set up the brickstrap environment
# - create a supermin appliance (not needed if you answered "y" during install
# - add yourself to the kvm group (requires login to take effect)
# - fix permissions on /boot/vmlinuz*

apt-get -y --no-install-recommends install proot
apt-get -y --no-install-recommends install brickstrap

update-guestfs-appliance

usermod -a -G kvm ${myUserName}
chmod +r /boot/vmlinuz*

# -----------------------------------------------------------------------------
# Install and set up the kernel build environment

apt-get -y --no-install-recommends install git
apt-get -y --no-install-recommends install kernel-package devscripts
apt-get -y --no-install-recommends install build-essential ncurses-dev u-boot-tools
apt-get -y --no-install-recommends install libc6-i386 fakeroot bc

# -----------------------------------------------------------------------------
