#!/bin/dash
# -----------------------------------------------------------------------------
# 30-postInstall-aptupdate
#
# This is one of a series of scripts that live in /root/postInstall. They are
# placed there to avoid being read by casual users and are intended to be
# executed immediately after the VM is created to set up host specific 
# configuration.
#
# Update the apt lists
# -----------------------------------------------------------------------------

. /root/postInstall/postInstall-setupvars

# -----------------------------------------------------------------------------
# Update the apt lists

apt-get clean
apt-get update

# -----------------------------------------------------------------------------
