#!/bin/dash
#
# -----------------------------------------------------------------------------
# 00-postinstall-setupvars.sh
#
# This is one of a series of scripts that live in /root/postInstall. They are
# placed there to avoid being read by casual users and are intended to be
# executed immediately after the VM is created to set up host specific 
# configuration.
#
# This file should be sourced from other *-postInstall-* shell scripts if they
# need to access any host-specific variables that would have been set up when
# the VM was being installed.
# -----------------------------------------------------------------------------
# Shell variables accessible to all scripts that source this script:

myHostName="ev3dev-tahr64"

myIPAddress="192.168.56.56"
myUserName="defaultuser"
myUserUID="defaultUID"
myUserGID="defaultGID"
myNFSDirectory="/home/${myUserName}/projects"

hostIPAddress="192.168.56.1"
hostUserName="hostuser"
hostNFSDirectory="/home/${hostUserName}/nfs/${myHostName}"

postInstallBackupDir="/root/backup"

# -----------------------------------------------------------------------------
# Create a backup directory if it does not yet exist

if [ ! -d "${postInstallBackupDir}" ]; then
    mkdir -p "${postInstallBackupDir}"
fi

# -----------------------------------------------------------------------------
