#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# 10-postInstall-backup-fstab
#
# This is one of a series of scripts that live in /root/postInstall. They are
# placed there to avoid being read by casual users and are intended to be
# executed immediately after the VM is created to set up host specific
# configuration.
#
# Checks to see if there's a backup for /etc/fstab - if not then it
# backs up the original if it exists
#
# Copyright (C) 2014-2015 Ralph Hempel <rhempel@hempeldesigngroup.com>
#
# See LICENSE for https://github.com/rhempel/pxeBoot
# -----------------------------------------------------------------------------

. /root/postInstall/postInstall-setupvars

# -----------------------------------------------------------------------------
# Check if there's already a backup

FILE="/etc/fstab"
BACKUP="${postInstallBackupDir}${FILE}"

if [[ -e "${FILE}" ]] && [[ ! -e "${BACKUP}" ]]; then
    echo "Backing up \"${FILE}\""
    cp --parents "${FILE}" "${BACKUP}"
fi

if [[ -e "${BACKUP}" ]]; then
    echo "Restoring original \"${FILE}\""
    cp "${BACKUP}" "${FILE}"
fi

# -----------------------------------------------------------------------------
