#!/bin/bash
# -----------------------------------------------------------------------------
# 40-postInstall-clear-apt
#
# This is one of a series of scripts that live in /root/postInstall. They are
# placed there to avoid being read by casual users and are intended to be
# executed immediately after the VM is created to set up host specific 
# configuration.
#
# Checks to see if there's a backup for /etc/hosts - if not then it
# backs up the original hosts if it exists and writes out a new one
#
# Copyright (C) 2014-2015 Ralph Hempel <rhempel@hempeldesigngroup.com>
#
# See LICENSE for https://github.com/rhempel/pxeBoot
# -----------------------------------------------------------------------------

. /root/postInstall/postInstall-setupvars

# -----------------------------------------------------------------------------
# Check if there's already a backup

FILE="/etc/apt/sources.list"
BACKUP="${postInstallBackupDir}${FILE}"

if [[ -e "${FILE}" ]] && [[ ! -e "${BACKUP}" ]]; then
    echo "Backing up \"${FILE}\""
    cp --parents "${FILE}" "${postInstallBackupDir}"    
fi

rm "/etc/apt/sources.list"

# -----------------------------------------------------------------------------
# Clobber the apt lists so that when we update from the ISO
# that's now mounted on the host, we actually get the updates

echo "Clobber the apt lists"

for f in /var/lib/apt/lists/*; do
        [[ -f "${f}" ]] && rm "${f}"
done

for f in /var/lib/apt/lists/partial/*; do
        [[ -f "${f}" ]] && rm "${f}"
done

# -----------------------------------------------------------------------------
