#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# 50-postInstall-apt-install
#
# This is one of a series of scripts that live in /root/postInstall. They are
# placed there to avoid being read by casual users and are intended to be
# executed immediately after the VM is created to set up host specific 
# configuration.
#
# Install base apps for this machine
#
# Copyright (C) 2014-2015 Ralph Hempel <rhempel@hempeldesigngroup.com>
#
# See LICENSE for https://github.com/rhempel/pxeBoot
# -----------------------------------------------------------------------------

. /root/postInstall/postInstall-setupvars

# -----------------------------------------------------------------------------
# Install base apps for this machine

apt-get -y --no-install-recommends install sudo ntp openssh-server nfs-common 

# -----------------------------------------------------------------------------
