#!/bin/bash
# -----------------------------------------------------------------------------
# 50-postInstall-user-update
#
# This is one of a series of scripts that live in /root/postInstall. They are
# placed there to avoid being read by casual users and are intended to be
# executed immediately after the VM is created to set up host specific 
# configuration.
#
# Update some fundamental settings for the default user
#
# Copyright (C) 2014-2015 Ralph Hempel <rhempel@hempeldesigngroup.com>
#
# See LICENSE for https://github.com/rhempel/pxeBoot
# -----------------------------------------------------------------------------

. /root/postInstall/postInstall-setupvars

# -----------------------------------------------------------------------------
# Create a group for the default user, and make them part of the sudo group

groupmod                   -g "${vmUserGID}"            "${vmUserName}"
usermod  -u "${vmUserUID}" -g "${vmUserGID}" -a -G sudo "${vmUserName}"

# -----------------------------------------------------------------------------
