#!/bin/bash
# -----------------------------------------------------------------------------
# 50-postInstall-userupdate
#
# This is one of a series of scripts that live in /root/postInstall. They are
# placed there to avoid being read by casual users and are intended to be
# executed immediately after the VM is created to set up host specific 
# configuration.
#
# Update some fundamental settings for the default user
# -----------------------------------------------------------------------------

. /root/postInstall/postInstall-setupvars

# -----------------------------------------------------------------------------
# Create a group for the default user, and make them part of the sudo group

groupmod                   -g "${myUserGID}"            "${myUserName}"
usermod  -u "${myUserUID}" -g "${myUserGID}" -a -G sudo "${myUserName}"

# -----------------------------------------------------------------------------
# Create the user's projects directory and mount it

mkdir -p "/home/${myUserName}/projects"
chown "${myUserName}":"${myUserName}" "/home/${myUserName}/projects"

mount "/home/${myUserName}/projects"

# -----------------------------------------------------------------------------
